name: Build Heroic, upload artifacts

on:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-deps
      - name: Build Windows Portable version
        run: yarn dist:win portable
        if: runner.os == 'Windows'
      - name: Build macOS x64 & arm64 versions
        run: yarn dist:mac --x64 --arm64 --publish=never
        env:
          GITHUB_TOKEN: ${{ secrets.workflowToken }}
          GH_TOKEN: ${{ secrets.workflowToken }}
          CSC_IDENTITY_AUTO_DISCOVERY: false
        if: runner.os == 'macOS'
      - name: Build and publish Snap version
        run: |
          sudo apt-get install --no-install-recommends -y snapcraft
          yarn dist:linux Snap --publish=never
        if: runner.os == 'Linux' && inputs.publish-snap
      - name: Build AppImage version
        run: yarn dist:linux AppImage --publish=never
        if: runner.os == 'Linux'
      - name: Upload built version
        uses: actions/upload-artifact@v3
        with:
          name: ${{ (matrix.os == 'windows-2022'  && 'win-portable'  ) ||
                    (matrix.os == 'macos-12'      && 'mac-x64'       ) ||
                    (matrix.os == 'ubuntu-22.04'  && 'linux-AppImage') }}
          path: ${{ (matrix.os == 'windows-2022'  && 'dist/Heroic*.exe'      ) ||
                    (matrix.os == 'macos-12'      && 'dist/Heroic*x64.dmg'   ) ||
                    (matrix.os == 'ubuntu-22.04'  && 'dist/Heroic-*.AppImage') }}
      - name: Upload macOS ARM version
        uses: actions/upload-artifact@v3
        with:
          name: mac-arm64
          path: dist/Heroic*arm64.dmg
        if: runner.os == 'macOS'
  
  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: linux-AppImage
        path: ./artifacts/linux-AppImage
        
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: win-portable
        path: ./artifacts/win-portable
        
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: mac-x64
        path: ./artifacts/mac-x64
        
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: mac-arm64
        path: ./artifacts/mac-arm64

    - name: Archive all artifacts
      run: zip -r Heroic-dev.zip ./artifacts/*

    - name: Get Heroic Version
      run: echo "version=$(jq -r '.version' package.json)" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: Heroic ${env.version}
        prerelease: true
        files: |
          ./artifacts/linux-AppImage/**
          ./artifacts/win-portable/**
          ./artifacts/mac-x64/**
          ./artifacts/mac-arm64/**
          Heroic-dev.zip
      env:
        GITHUB_TOKEN: ${{ secrets.workflowToken }}
